//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbBASOSModel", "FK_Lugares_Lugares", "Tipos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SOSService1.Tipos), "Lugares", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SOSService1.Lugares), true)]

#endregion

namespace SOSService1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbBASOSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbBASOSEntities object using the connection string found in the 'dbBASOSEntities' section of the application configuration file.
        /// </summary>
        public dbBASOSEntities() : base("name=dbBASOSEntities", "dbBASOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbBASOSEntities object.
        /// </summary>
        public dbBASOSEntities(string connectionString) : base(connectionString, "dbBASOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbBASOSEntities object.
        /// </summary>
        public dbBASOSEntities(EntityConnection connection) : base(connection, "dbBASOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lugares> Lugares
        {
            get
            {
                if ((_Lugares == null))
                {
                    _Lugares = base.CreateObjectSet<Lugares>("Lugares");
                }
                return _Lugares;
            }
        }
        private ObjectSet<Lugares> _Lugares;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tipos> Tipos
        {
            get
            {
                if ((_Tipos == null))
                {
                    _Tipos = base.CreateObjectSet<Tipos>("Tipos");
                }
                return _Tipos;
            }
        }
        private ObjectSet<Tipos> _Tipos;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lugares EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLugares(Lugares lugares)
        {
            base.AddObject("Lugares", lugares);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tipos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipos(Tipos tipos)
        {
            base.AddObject("Tipos", tipos);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbBASOSModel", Name="Lugares")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lugares : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lugares object.
        /// </summary>
        /// <param name="lugarID">Initial value of the LugarID property.</param>
        /// <param name="tipoID">Initial value of the TipoID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Lugares CreateLugares(global::System.Int32 lugarID, global::System.Int32 tipoID, global::System.String nombre)
        {
            Lugares lugares = new Lugares();
            lugares.LugarID = lugarID;
            lugares.TipoID = tipoID;
            lugares.Nombre = nombre;
            return lugares;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LugarID
        {
            get
            {
                return _LugarID;
            }
            set
            {
                if (_LugarID != value)
                {
                    OnLugarIDChanging(value);
                    ReportPropertyChanging("LugarID");
                    _LugarID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LugarID");
                    OnLugarIDChanged();
                }
            }
        }
        private global::System.Int32 _LugarID;
        partial void OnLugarIDChanging(global::System.Int32 value);
        partial void OnLugarIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TipoID
        {
            get
            {
                return _TipoID;
            }
            set
            {
                OnTipoIDChanging(value);
                ReportPropertyChanging("TipoID");
                _TipoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoID");
                OnTipoIDChanged();
            }
        }
        private global::System.Int32 _TipoID;
        partial void OnTipoIDChanging(global::System.Int32 value);
        partial void OnTipoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Barrio
        {
            get
            {
                return _Barrio;
            }
            set
            {
                OnBarrioChanging(value);
                ReportPropertyChanging("Barrio");
                _Barrio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Barrio");
                OnBarrioChanged();
            }
        }
        private global::System.String _Barrio;
        partial void OnBarrioChanging(global::System.String value);
        partial void OnBarrioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Circunscripcion
        {
            get
            {
                return _Circunscripcion;
            }
            set
            {
                OnCircunscripcionChanging(value);
                ReportPropertyChanging("Circunscripcion");
                _Circunscripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Circunscripcion");
                OnCircunscripcionChanged();
            }
        }
        private global::System.String _Circunscripcion;
        partial void OnCircunscripcionChanging(global::System.String value);
        partial void OnCircunscripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DireccionNormalizada
        {
            get
            {
                return _DireccionNormalizada;
            }
            set
            {
                OnDireccionNormalizadaChanging(value);
                ReportPropertyChanging("DireccionNormalizada");
                _DireccionNormalizada = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DireccionNormalizada");
                OnDireccionNormalizadaChanged();
            }
        }
        private global::System.String _DireccionNormalizada;
        partial void OnDireccionNormalizadaChanging(global::System.String value);
        partial void OnDireccionNormalizadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comuna
        {
            get
            {
                return _Comuna;
            }
            set
            {
                OnComunaChanging(value);
                ReportPropertyChanging("Comuna");
                _Comuna = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comuna");
                OnComunaChanged();
            }
        }
        private global::System.String _Comuna;
        partial void OnComunaChanging(global::System.String value);
        partial void OnComunaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Geocodificacion
        {
            get
            {
                return _Geocodificacion;
            }
            set
            {
                OnGeocodificacionChanging(value);
                ReportPropertyChanging("Geocodificacion");
                _Geocodificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Geocodificacion");
                OnGeocodificacionChanged();
            }
        }
        private global::System.String _Geocodificacion;
        partial void OnGeocodificacionChanging(global::System.String value);
        partial void OnGeocodificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> X
        {
            get
            {
                return _X;
            }
            set
            {
                OnXChanging(value);
                ReportPropertyChanging("X");
                _X = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X");
                OnXChanged();
            }
        }
        private Nullable<global::System.Double> _X;
        partial void OnXChanging(Nullable<global::System.Double> value);
        partial void OnXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y
        {
            get
            {
                return _Y;
            }
            set
            {
                OnYChanging(value);
                ReportPropertyChanging("Y");
                _Y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Y");
                OnYChanged();
            }
        }
        private Nullable<global::System.Double> _Y;
        partial void OnYChanging(Nullable<global::System.Double> value);
        partial void OnYChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbBASOSModel", "FK_Lugares_Lugares", "Tipos")]
        public Tipos Tipos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tipos>("dbBASOSModel.FK_Lugares_Lugares", "Tipos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tipos>("dbBASOSModel.FK_Lugares_Lugares", "Tipos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tipos> TiposReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tipos>("dbBASOSModel.FK_Lugares_Lugares", "Tipos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tipos>("dbBASOSModel.FK_Lugares_Lugares", "Tipos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbBASOSModel", Name="Tipos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tipos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tipos object.
        /// </summary>
        /// <param name="tipoID">Initial value of the TipoID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Tipos CreateTipos(global::System.Int32 tipoID, global::System.String nombre)
        {
            Tipos tipos = new Tipos();
            tipos.TipoID = tipoID;
            tipos.Nombre = nombre;
            return tipos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TipoID
        {
            get
            {
                return _TipoID;
            }
            set
            {
                if (_TipoID != value)
                {
                    OnTipoIDChanging(value);
                    ReportPropertyChanging("TipoID");
                    _TipoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TipoID");
                    OnTipoIDChanged();
                }
            }
        }
        private global::System.Int32 _TipoID;
        partial void OnTipoIDChanging(global::System.Int32 value);
        partial void OnTipoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbBASOSModel", "FK_Lugares_Lugares", "Lugares")]
        public EntityCollection<Lugares> Lugares
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lugares>("dbBASOSModel.FK_Lugares_Lugares", "Lugares");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lugares>("dbBASOSModel.FK_Lugares_Lugares", "Lugares", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
